@ECHO OFF
S:
MAKE.EXE CLEAN
MAKE.EXE

IMGMOUNT A BOOTFL.IMG
A:
MD XOSL
XCOPY D:\*.BIN A:\XOSL /S /E /V /R /Y
XCOPY D:\*.EXE A:\XOSL /S /E /V /R /Y
XCOPY D:\*.MBR A:\XOSL /S /E /V /R /Y
XCOPY D:\*.TXT A:\XOSL /S /E /V /R /Y
XCOPY D:\*.XBF A:\XOSL /S /E /V /R /Y
XCOPY D:\*.XCF A:\XOSL /S /E /V /R /Y
XCOPY D:\*.XFF A:\XOSL /S /E /V /R /Y
XCOPY D:\*.XXF A:\XOSL /S /E /V /R /Y
IMGMOUNT A -U

IMGMOUNT A BOOTFLRD.IMG
A:
MD XOSL
XCOPY D:\*.BIN A:\XOSL /S /E /V /R /Y
XCOPY D:\*.EXE A:\XOSL /S /E /V /R /Y
XCOPY D:\*.MBR A:\XOSL /S /E /V /R /Y
XCOPY D:\*.TXT A:\XOSL /S /E /V /R /Y
XCOPY D:\*.XBF A:\XOSL /S /E /V /R /Y
XCOPY D:\*.XCF A:\XOSL /S /E /V /R /Y
XCOPY D:\*.XFF A:\XOSL /S /E /V /R /Y
XCOPY D:\*.XXF A:\XOSL /S /E /V /R /Y
IMGMOUNT A -U